name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip & install build tools
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools

      - name: Install dependencies
        run: |
          if [ "${{ matrix.python-version }}" = "3.13" ]; then
            # Pin pandas & numpy for Python 3.13 to avoid build issues
            pip install "numpy<2.0.0" "pandas==2.2.2"
          fi
          pip install -r requirements.txt
          pip install pytest rich

      - name: Run all scenarios and validate artifacts
        run: |
          make run-all
          python tools/validate_artifacts.py

      - name: Run tests
        run: pytest -q

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.python-version }}
          path: artifacts
