name: CI: tests + scenarios + artifacts

on:
  push:
  pull_request:

jobs:
  tests:
    name: tests (${{ matrix.python-version }})
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
        os: [ ubuntu-latest ]
        include:
          # Run 3.13 on macOS so we get prebuilt wheels for pinned deps.
          - python-version: "3.13"
            os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (pinned)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: make test

  run-scenarios:
    name: Run Scenarios + Artifacts
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (pinned)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run all scenarios
        run: make run-all

      - name: Validate JSON artifacts
        run: python tools/validate_artifacts.py

      - name: Upload artifacts (CSV + JSON)
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ github.sha }}
          path: artifacts/**
          if-no-files-found: error
          retention-days: 14
