name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip & install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies (with 3.13 pins)
        run: |
          if [[ "${{ matrix.python-version }}" == "3.13" ]]; then
            # Pin dependencies known to work with 3.13
            pip install pandas==2.2.2 numpy==1.26.4
          fi
          pip install -r requirements.txt

      - name: Run all scenarios and generate JSON
        run: |
          make run-all
          python tools/validate_artifacts.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: collapse_artifacts-${{ matrix.python-version }}
          path: artifacts/
